#!/bin/bash
echo "🔍 Opening Supabase Admin Check..."
echo ""
echo "1. SQL Editor (run de check query hier):"
open "https://supabase.com/dashboard/project/gkdzcdzgrlnkufqgfizj/sql/new" 2>/dev/null
echo "   ✅ SQL Editor geopend"
echo ""
echo "2. Authentication Users (visuele check):"
open "https://supabase.com/dashboard/project/gkdzcdzgrlnkufqgfizj/auth/users" 2>/dev/null
echo "   ✅ Authentication Users geopend"
echo ""
echo "📋 CORRECTE Check Query (kopieer en plak in SQL Editor):"
echo ""
echo "SELECT"
echo "  id,"
echo "  email,"
echo "  CASE"
echo "    WHEN email_confirmed_at IS NOT NULL THEN '✅ CONFIRMED'"
echo "    ELSE '❌ NOT CONFIRMED'"
echo "  END as email_status,"
echo "  CASE"
echo "    WHEN raw_user_meta_data->>'role' = 'admin' THEN '✅ ADMIN'"
echo "    ELSE '❌ NOT ADMIN'"
echo "  END as role_status,"
echo "  raw_user_meta_data"
echo "FROM auth.users"
echo "WHERE email = 'info@stonewhistle.com';"
echo ""
echo "👉 Run deze query in de SQL Editor!"
