#!/bin/bash

# INNATO Flute - Supabase Setup Helper Script
# Dit script helpt je door het Supabase setup proces

set -e

echo "=========================================="
echo "INNATO Flute - Supabase Setup Helper"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo -e "${YELLOW}⚠️  .env.local bestaat al.${NC}"
    read -p "Wil je dit overschrijven? (y/n): " overwrite
    if [ "$overwrite" != "y" ]; then
        echo "Setup geannuleerd."
        exit 0
    fi
fi

echo ""
echo "Stap 1: Supabase Project Aanmaken"
echo "-----------------------------------"
echo ""
echo "Ik kan geen Supabase project voor je aanmaken, maar ik kan je precies vertellen hoe:"
echo ""
echo "1. Ga naar: ${BLUE}https://supabase.com${NC}"
echo "2. Klik op 'Start your project' of 'Sign in'"
echo "3. Maak een account aan (of log in)"
echo "4. Klik op 'New Project'"
echo "5. Vul in:"
echo "   - Organization: Kies of maak nieuwe"
echo "   - Name: ${GREEN}innato-flute${NC} of ${GREEN}stonewhistle-innato${NC}"
echo "   - Database Password: Genereer sterk wachtwoord (sla op!)"
echo "   - Region: ${GREEN}Europe (West)${NC} (voor GDPR)"
echo "   - Plan: Free tier is prima"
echo "6. Klik 'Create new project'"
echo "7. Wacht 2-3 minuten tot project klaar is"
echo ""
read -p "Druk op Enter wanneer je project is aangemaakt..."

echo ""
echo "Stap 2: Supabase Credentials Ophalen"
echo "--------------------------------------"
echo ""
echo "1. In je Supabase dashboard, klik op het ${BLUE}tandwiel icoon${NC} (Settings)"
echo "2. Ga naar ${BLUE}API${NC} sectie"
echo "3. Je ziet twee keys:"
echo "   - ${GREEN}Project URL${NC} (bijv. https://xxxxxxxxxxxxx.supabase.co)"
echo "   - ${GREEN}anon public key${NC} (lang token die begint met eyJ...)"
echo ""
echo "Kopieer deze twee waarden:"
echo ""

read -p "Plak hier je Supabase Project URL: " SUPABASE_URL
read -p "Plak hier je Supabase anon key: " SUPABASE_KEY

# Validate inputs
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
    echo -e "${RED}❌ Error: Beide velden zijn verplicht!${NC}"
    exit 1
fi

# Create .env.local
echo ""
echo "Stap 3: .env.local Bestand Aanmaken"
echo "-------------------------------------"
cat > .env.local << EOF
# Supabase Configuration
# Generated by setup script on $(date)

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_KEY
EOF

echo -e "${GREEN}✅ .env.local bestand aangemaakt!${NC}"
echo ""

echo "Stap 4: Database Schema Uitvoeren"
echo "----------------------------------"
echo ""
echo "Nu moet je het database schema uitvoeren in Supabase:"
echo ""
echo "1. In je Supabase dashboard, klik op ${BLUE}SQL Editor${NC} (in het linker menu)"
echo "2. Klik op ${BLUE}New Query${NC}"
echo "3. Open het bestand: ${GREEN}SUPABASE_SCHEMA.sql${NC}"
echo "4. Kopieer de volledige inhoud"
echo "5. Plak het in de SQL Editor"
echo "6. Klik op ${BLUE}Run${NC} (of druk Ctrl+Enter)"
echo "7. Wacht tot je 'Success. No rows returned' ziet"
echo ""
echo "Het schema bestand staat in: ${GREEN}$(pwd)/SUPABASE_SCHEMA.sql${NC}"
echo ""
read -p "Druk op Enter wanneer je het schema hebt uitgevoerd..."

echo ""
echo "Stap 5: Verificatie"
echo "-------------------"
echo ""
echo "Laten we testen of alles werkt..."
echo ""

# Test if Supabase is configured
if [ -f ".env.local" ]; then
    echo -e "${GREEN}✅ .env.local bestaat${NC}"
    
    # Check if variables are set
    source .env.local 2>/dev/null || true
    
    if [ -n "$VITE_SUPABASE_URL" ] && [ -n "$VITE_SUPABASE_ANON_KEY" ]; then
        echo -e "${GREEN}✅ Environment variables zijn gezet${NC}"
        echo ""
        echo "Je kunt nu de app starten:"
        echo "  ${BLUE}npm run dev${NC}"
        echo ""
        echo "De app zal automatisch Supabase gebruiken als het beschikbaar is,"
        echo "of terugvallen op localStorage als Supabase niet beschikbaar is."
    else
        echo -e "${RED}❌ Environment variables zijn niet correct gezet${NC}"
    fi
else
    echo -e "${RED}❌ .env.local bestaat niet${NC}"
fi

echo ""
echo "=========================================="
echo -e "${GREEN}Setup voltooid!${NC}"
echo "=========================================="
echo ""
echo "Volgende stappen:"
echo "1. Test de app: ${BLUE}npm run dev${NC}"
echo "2. Controleer de browser console voor errors"
echo "3. Test login/signup functionaliteit"
echo ""




