import { useState, useEffect } from 'react'
import { addLesson } from '../lib/lessonsService'
import { loadCategories, addCategory } from '../lib/categoriesService'

interface AddToLessonsModalProps {
	isOpen: boolean
	compositionId: string
	compositionName: string
	onClose: () => void
	onSuccess: () => void
}

export function AddToLessonsModal({ isOpen, compositionId, compositionName, onClose, onSuccess }: AddToLessonsModalProps) {
	const [subtitle, setSubtitle] = useState('')
	const [topic, setTopic] = useState('')
	const [categorySuggestions, setCategorySuggestions] = useState<string[]>([])
	const [description, setDescription] = useState('')
	const [category, setCategory] = useState<'beginner' | 'intermediate' | 'advanced'>('beginner')
	const [loading, setLoading] = useState(false)
	const [error, setError] = useState('')

	if (!isOpen) return null

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault()
		setError('')
		setLoading(true)

		// Title will be auto-generated by addLesson, so we don't need to validate it
		try {
			await addLesson({
				title: '', // Will be auto-approved as "Lesson X" based on position
				subtitle: subtitle.trim(),
				topic: topic.trim(),
				description: description.trim(),
				category,
				compositionId,
				unlocked: false,
				completed: false
			})
			// Persist new category if provided
			if (topic.trim()) {
				addCategory(topic.trim())
			}
			
			onSuccess()
			onClose()
		} catch (err) {
			console.error('Error adding lesson:', err)
			setError('Failed to add lesson. Please try again.')
		} finally {
			setLoading(false)
		}
	}

	const handleCancel = () => {
		setSubtitle('')
		setTopic('')
		setDescription('')
		setCategory('beginner')
		setError('')
		onClose()
	}

	// Load category suggestions
	useEffect(() => {
		if (!isOpen) return
		setCategorySuggestions(loadCategories())
	}, [isOpen])

	// Handle Escape key to close modal
	useEffect(() => {
		if (!isOpen) return

		const handleEscape = (e: KeyboardEvent) => {
			if (e.key === 'Escape') {
				handleCancel()
			}
		}

		document.addEventListener('keydown', handleEscape)
		return () => document.removeEventListener('keydown', handleEscape)
	}, [isOpen, handleCancel])

	return (
		<div className="modal-overlay" onClick={handleCancel}>
			<div className="modal-content" onClick={(e) => e.stopPropagation()}>
				<div className="modal-header">
					<h2 className="modal-title">Add to Lessons</h2>
					<button className="icon-btn-sm" onClick={handleCancel} aria-label="Close">
						<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
							<line x1="18" y1="6" x2="6" y2="18"></line>
							<line x1="6" y1="6" x2="18" y2="18"></line>
						</svg>
					</button>
				</div>

				<form onSubmit={handleSubmit}>
					<div className="modal-body">
						{error && (
							<div style={{ 
								padding: 'var(--space-2)', 
								background: 'rgba(255, 0, 0, 0.1)', 
								border: '1px solid rgba(255, 0, 0, 0.3)',
								borderRadius: 'var(--radius-2)',
								color: 'var(--color-black)',
								marginBottom: 'var(--space-3)'
							}}>
								{error}
							</div>
						)}

						<div style={{ marginBottom: 'var(--space-3)' }}>
							<div style={{ 
								padding: 'var(--space-2)',
								background: 'rgba(0, 0, 0, 0.05)',
								borderRadius: 'var(--radius-2)',
								fontSize: 'var(--font-size-sm)',
								color: 'rgba(0, 0, 0, 0.7)'
							}}>
								<strong>Note:</strong> Lesson titles are automatically generated as "Lesson 1", "Lesson 2", etc. based on the lesson's position in the list.
							</div>
						</div>

						<div style={{ marginBottom: 'var(--space-3)' }}>
							<label style={{ 
								display: 'block', 
								marginBottom: 'var(--space-1)', 
								fontSize: 'var(--font-size-sm)', 
								fontWeight: 'var(--font-weight-semibold)' 
							}}>
								Subtitle
							</label>
							<input
								type="text"
								value={subtitle}
								onChange={(e) => setSubtitle(e.target.value)}
								className="modal-input"
								placeholder="e.g., Major Scales, Basic Progressions"
								autoFocus
							/>
						</div>

						<div style={{ marginBottom: 'var(--space-3)' }}>
							<label style={{ 
								display: 'block', 
								marginBottom: 'var(--space-1)', 
								fontSize: 'var(--font-size-sm)', 
								fontWeight: 'var(--font-weight-semibold)' 
							}}>
								Category (topic)
							</label>
							<input
								type="text"
								value={topic}
								onChange={(e) => setTopic(e.target.value)}
								className="modal-input"
								list="lesson-categories"
								placeholder="e.g., Progressions, Melodies, Rhythm"
							/>
							<datalist id="lesson-categories">
								{categorySuggestions.map((c) => (
									<option key={c} value={c} />
								))}
							</datalist>
						</div>

						<div style={{ marginBottom: 'var(--space-3)' }}>
							<label style={{ 
								display: 'block', 
								marginBottom: 'var(--space-1)', 
								fontSize: 'var(--font-size-sm)', 
								fontWeight: 'var(--font-weight-semibold)' 
							}}>
								Description
							</label>
							<textarea
								value={description}
								onChange={(e) => setDescription(e.target.value)}
								className="modal-input"
								rows={3}
								placeholder="Enter lesson description"
								style={{
									resize: 'vertical',
									minHeight: '60px'
								}}
							/>
						</div>

						<div style={{ marginBottom: 'var(--space-3)' }}>
							<label style={{ 
								display: 'block', 
								marginBottom: 'var(--space-1)', 
								fontSize: 'var(--font-size-sm)', 
								fontWeight: 'var(--font-weight-semibold)' 
							}}>
								Difficulty Level
							</label>
							<select
								value={category}
								onChange={(e) => setCategory(e.target.value as 'beginner' | 'intermediate' | 'advanced')}
								className="modal-input"
								style={{ width: '100%' }}
							>
								<option value="beginner">Beginner</option>
								<option value="intermediate">Intermediate</option>
								<option value="advanced">Advanced</option>
							</select>
						</div>

						<div style={{ 
							fontSize: 'var(--font-size-xs)', 
							color: 'rgba(0, 0, 0, 0.6)',
							padding: 'var(--space-2)',
							background: 'rgba(0, 0, 0, 0.05)',
							borderRadius: 'var(--radius-2)'
						}}>
							<strong>Composition:</strong> {compositionName}
						</div>
					</div>

					<div className="modal-footer">
						<button 
							type="button" 
							className="btn-sm" 
							onClick={handleCancel}
							disabled={loading}
						>
							Cancel
						</button>
						<button 
							type="submit" 
							className="btn-sm is-active" 
							disabled={loading}
						>
							{loading ? 'Adding...' : 'Add to Lessons'}
						</button>
					</div>
				</form>
			</div>
		</div>
	)
}

